#USER ---------------------------------------------------
ldapApprovalGroup: sony,test,admin

#Deploy--------------------------------------------------------

approvalTimeout: 15
approvalTimeoutUnit: 'MINUTES'
abortReasonTimeout: 10
abortReasonTimeoutUnit: 'MINUTES'

#DeployApproval--------------------------------------------------------
ApprovalGroup: sony,admi
emailApprovalRecipients:  shanmugam.nsw@gmail.com
emailOutageRecipients: shanmugam.nsw@gmail.com

#service---------------
vault: apple,mango,Two
